platform :ios, '8.0'
target:qmcp do
    pod 'MBProgressHUD', '0.9.2'
    pod 'RESideMenu', '4.0.7'
    pod 'AFNetworking', '3.1.0'
    pod 'SAMKeychain'
    pod 'MJExtension', '3.0.10'
    pod 'FMDB', '2.6.2'
    pod 'LKDBHelper', '2.2'
    pod 'FontAwesome', '4.5.0'
    pod 'MJRefresh', '3.1.12'
    pod 'ReactiveCocoa', '2.5'
    pod 'Masonry', '1.0.0'
    pod 'TMCache', '2.1.0'
    pod 'JazzHands', '2.0.0'
    pod 'NYXImagesKit', '2.3'
    pod 'ActionSheetPicker-3.0','2.2.0'
    pod 'SDWebImage','3.8.1'
    pod 'AMap2DMap','4.1.0'
    pod 'AMapLocation','2.1.0'
    pod 'YCXMenu', '~> 0.0.11'
    pod 'SDAutoLayout', '~> 2.1.3'
    pod 'GTSDK'
    pod 'FLEX', :configurations => ['Debug']
end
