platform :ios, '7.0'
target :qmcp do
    pod 'MBProgressHUD', '1.0.0'
    pod 'RESideMenu', '4.0.7'
    pod 'AFNetworking', '3.1.0'
    pod 'SSKeychain', '1.4.0'
    pod 'MJExtension', '3.0.10'
    pod 'FMDB', '2.6.2'
    pod 'LKDBHelper', '2.2'
    pod 'FontAwesome', '4.5.0'
    pod 'MJRefresh', '3.1.0'
    pod 'ReactiveCocoa', '2.5'
    pod 'Masonry', '1.0.0'
    pod 'TMCache’, '2.1.0'
    pod 'JazzHands', '2.0.0'
    pod 'NYXImagesKit', '2.3'
    pod 'ActionSheetPicker-3.0'
    pod 'SDWebImage', '~>3.8'
    pod 'AMap2DMap'
    pod 'AMapLocation'
end
