platform :ios, '7.0'
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'

pod 'MBProgressHUD', '0.9.2'
pod 'RESideMenu', '4.0.7'
pod 'GPUImage', '0.1.7'
pod 'AFNetworking', '3.1.0'
pod 'SSKeychain', '1.4.0'
pod 'MJExtension', '3.0.10'
pod 'FMDB', '2.6.2'
pod 'LKDBHelper', '2.2'
pod 'FontAwesome', '4.5.0'
pod 'MJRefresh', '3.1.0'
pod 'ReactiveCocoa', '2.5'
pod 'Masonry', '1.0.0'
pod 'TMCache’, '2.1.0'
pod 'JazzHands', '2.0.0'
pod 'NYXImagesKit', '2.3'